#ifndef SDKCONFIG_H
#define SDKCONFIG_H

/* Convenience fallback sdkconfig for ESP32-S3 (NOT generated by menuconfig).
   This file provides minimal CONFIG_* macros to allow building under Arduino
   when an actual sdkconfig.h is not present. For production builds, generate
   a proper sdkconfig using ESP-IDF `idf.py menuconfig` and add it to the project root.
*/

/* Target */
#define IDF_TARGET_ESP32S3
#define CONFIG_IDF_TARGET_ESP32S3 1
#define IDF_TARGET "esp32s3"

/* FreeRTOS */
#define CONFIG_FREERTOS_HZ 1000
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_MAX_PRIORITIES 25

/* LWIP / DHCP */
#define CONFIG_LWIP_DHCP_COARSE_TIMER_SECS 10
#define CONFIG_LWIP_DHCP_DOES_ARP_CHECK 1
#define CONFIG_LWIP_DHCP_DISABLE_CLIENT_ID 0
#define CONFIG_LWIP_DHCP_RESTORE_LAST_IP 0
#define CONFIG_LWIP_TCP_SYNMAXRTX 6

/* TCP oversize - choose one option to satisfy lwipopts.h */
#define CONFIG_LWIP_TCP_OVERSIZE_DISABLE 1

/* PSRAM / heap */
#define CONFIG_SPIRAM_SUPPORT 1
#define CONFIG_SPIRAM_USE_MALLOC 1

/* Bluetooth / WiFi */
#define CONFIG_BT_ENABLED 1
#define CONFIG_BLUEDROID_ENABLED 1
#define CONFIG_WIFI_ENABLED 1

/* GPIO / SOC */
#define CONFIG_SOC_GPIO_SUPPORTED 1

/* Misc */
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ 240

#endif // SDKCONFIG_H
